server:
  port: 8080
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: CommFilterController
          args:
            baseMessage: Spring Cloud Gateway CommFilter
            preLogger: true
            postLogger: true
      routes:
        - id: menu-svc
          uri: http://localhost:8081/
          predicates:
            - Path=/menu/**
          filters:
            - name: MenuFilterController
              args:
                baseMessage: Spring Cloud Gateway MenuFilter
                preLogger: true
                postLogger: true
        - id: user-svc
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**
          filters:
            - name: UserFilterController
              args:
                baseMessage: Spring Cloud Gateway UserFilter
                preLogger: true
                postLogger: true
        - id: order-svc
          uri: http://localhost:8083/
          predicates:
            - Path=/order/**
          filters:
            - name: OrderFilterController
              args:
                baseMessage: Spring Cloud Gateway OrderFilter
                preLogger: true
                postLogger: true